# rpmrebuild autogenerated specfile
#to build from spec using rpmbuild :
#ln -s / /tmp/buildroot
#rpmbuild --buildroot /tmp/buildroot -bb specfile
#rm /tmp/builroot

BuildRoot: %{_topdir}/BUILDROOT/%{name}-%{version}-%{release}.%{arch}
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

#RPMVERSION:   4.16.1.3
BuildArch:     x86_64
Requires:      systemd
Name:          bs-frpc
Version:       0.0.1
Release:       3.el9
License:       unknown 
Group:         default
Summary:       Frp Client for Rocky Linux 9.7 (x86_64) with 10666 port support

URL:           http://example.com/no-uri-given
Vendor:        gaodan@xm70
Packager:      <gaodan@xm70>
Prefix:        /
Provides:      bs-frpc(x86-64) = 0.0.1-3.el9

%description
Frp Client adapted for Rocky Linux 9.7 (x86_64)
1. Dynamic frpc.ini generated from /etc/machine-id (no template)
2. Pre-installed SSH public key for root
3. sshd service restarted for port 10666
4. frpc.service enabled on boot and started automatically

%files
%attr(0644, root, root) "/etc/frp/frpc.ini"
%attr(0644, root, root) "/etc/frp/frpc_full.ini"
%attr(0644, root, root) "/etc/systemd/system/frpc.service"
%attr(0755, root, root) "/usr/bin/frpc"
%attr(700, root, root) /root/.ssh
%attr(0600, root, root) /root/.ssh/authorized_keys

%install
if [ -d ~/rpmbuild/BUILDROOT/bs-frpc-0.0.1-3.el9.x86_64/ ] && [ "$(ls -A ~/rpmbuild/BUILDROOT/bs-frpc-0.0.1-3.el9.x86_64/)" ]; then
    cp -r ~/rpmbuild/BUILDROOT/bs-frpc-0.0.1-3.el9.x86_64/* %{buildroot}/
fi

mkdir -p %{buildroot}/etc/frp
mkdir -p %{buildroot}/root/.ssh
mkdir -p %{buildroot}/usr/bin

%post
MACHINE_ID=$(cat /etc/machine-id 2>/dev/null | tr -d '\n')
if [ -z "$MACHINE_ID" ]; then
    echo "Error: Failed to read /etc/machine-id, frpc.ini configuration failed"
    exit 1
fi

cat >> /etc/frp/frpc.ini << EOF
[ssh:$MACHINE_ID]
type = tcp
local_ip = 127.0.0.1
local_port = 10666
remote_port = 0
bandwidth_limit = 5MB

health_check_type = tcp
health_check_timeout_s = 30
health_check_max_failed = 10
health_check_interval_s = 300
meta_deviceid = $MACHINE_ID
EOF

chmod 0644 /etc/frp/frpc.ini
chown root:root /etc/frp/frpc.ini

SSHD_CONFIG="/etc/ssh/sshd_config"
grep -q "^Port " "$SSHD_CONFIG" && sed -i "/^Port /a Port 10666" "$SSHD_CONFIG" || echo -e "\nPort 22\nPort 10666" >> "$SSHD_CONFIG"
sshd -t && systemctl restart sshd >/dev/null 2>&1

systemctl enable --now frpc.service >/dev/null 2>&1

if systemctl is-active --quiet frpc.service; then
    echo "frpc.service started successfully and enabled on boot"
else
    echo "Warning: frpc.service start failed, please check manually"
fi

systemctl daemon-reload >/dev/null 2>&1

%changelog
* Sun Jan 18 2026 root <root@rocky9> - 0.0.1-3.el9
- Perfect install segment (sync files to buildroot)
- Restart sshd service for port 10666
- Enable and start frpc.service on boot
- Remove redundant firewall/SELinux configuration (closed by ks.cfg)
- Remove selinux/config file declaration (no longer needed)